### ISSUE TITLE
What does the library use antd for? Possible to exclude it?

### ISSUE THREAD

**Issue by Slapbox** [Canner/slate-md-editor#28]
I've been meaning to test this in a real use case for a long time now, but it's an incredible headache to get working because of the incredible headache `antd` is to get working. I've followed all the guides, but I still have trouble loading the styles from `antd` in Webpack.

I'm sure I'm eventually going to get it working, but is there a way to just use this library without it?

**Comment by Slapbox** [comment]
I did manage to get it working. I previously used `antd` in a trial and packaging my Electron application, the size went up something like 9mb (~12%), so I'm definitely still interested in using the plugin without `antd` in a sustainable way. Any thoughts on that front?

**Comment by chilijung** [comment]
Sorry `antd` is needed because some of the UI's such as tooltips, icons, grids, image loader... are all based on `antd`. So currently it is not possible.

However, you could set `antd` as external package in webpack and import it from CDN. Which can reduce all the bundle size in your applications.

**Comment by Slapbox** [comment]
Thanks very much for your reply @chilijung.
